name: Run MATLAB Tests

on:
  push:
    branches:
      - main  # Runs tests when code is pushed to main
  pull_request:
    branches:
      - main  # Runs tests when a PR is opened to main

jobs:
  run-matlab-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clones the repo

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1  # Official MATLAB GitHub Action

      - name: Run MATLAB Test Script
        uses: matlab-actions/run-command@v1
        with:
          command: |
            try
                power_calculator_test_script;
                disp('All tests passed successfully.');
            catch ME
                disp('Test failed.');
                disp(ME.message);
                exit(1);
            end
            
