name: Run MATLAB Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-matlab-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v1
      
    - name: Install required system libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        
    - name: Run MATLAB Test Script
      uses: matlab-actions/run-command@v1
      with:
        command: |
          try
            global testing_yml_workflow;
            testing_yml_workflow = true; % Indicate CI/CD mode
            
            % Display compiler information
            disp('C++ Compiler Information:');
            mex -setup cpp
            
            % Run the test script
            power_calculator_test_script;
            disp('All tests passed successfully.');
          catch ME
            disp('Test failed.');
            disp(ME.message);
            disp(getReport(ME, 'extended'));
            exit(1);
          end
